appconfig:
   baseUrl: http://192.168.1.3:15555/
   lib: 0
   startIndex: 0
   endIndex: 2000
   selectionSize: 2
   saveDir: images

logging:
  file: application.log
  level:
    ro.vdin: DEBUG
#    org.apache.http: DEBUG
#    org.apache.http.wire: DEBUG
